# general
seed: 42
workers: 8
dataset_dir: "./datasets"

# train options
batch_size: 64
image_size: 60 #upscaled to 224, this leads to blurred images
start_epoch: 1000
epochs: 1000
dataset: "FPI" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet / FASHION-MNIST

# model options
resnet: "ResNet34" # ResNet18 / ResNet34 / ResNet50
feature_dim: 128
model_path: "save/FPI"
reload: False

# loss options
learning_rate: 0.0003
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
